apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-service-config
  namespace: aiops
data:
  LOG_LEVEL: "INFO"
  ENV_NAME: "sandbox"
  AWS_REGION: "us-east-1"
  JIRA_URL: "https://nguyenanhhoang1482004.atlassian.net"
  JIRA_USER: "phuockhoamai@gmail.com"
  JIRA_PROJECT_KEY: "alert"
  SQS_QUEUE_URL: ""
  AI_ENGINE_URL: "http://ai-engine:8080"
