apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-service-secrets
  namespace: aiops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: platform-service-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: JIRA_API_TOKEN
      remoteRef:
        key: tf1-triage-hub-sandbox/jira-api-token
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: tf1-triage-hub-sandbox/slack-webhook-url
    - secretKey: SERVICE_AUTH_TOKEN
      remoteRef:
        key: tf1-triage-hub-sandbox/service-auth-token
