# Cấu hình Grafana
grafana:
  enabled: true
  adminPassword: "admin" # Mật khẩu mặc định để test nội bộ
  ingress:
    enabled: true # Đã bật NGINX Ingress Controller
  # Tắt HA (High Availability) cho Grafana ở Sandbox
  replicas: 1
